version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-nextjs-app
permissions:
  - object: /home/ubuntu/my-nextjs-app
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: ubuntu
