version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-nextjs-app
permissions:
  - object: /home/ubuntu/my-nextjs-app/scripts/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  Install:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
