name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Zip Deployment Package
        run: zip -r deploy.zip . -x "node_modules/*" ".git/*"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload to S3
        run: aws s3 cp deploy.zip s3://${{ secrets.AWS_S3_BUCKET }}/

      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment --application-name NextjsApp \
            --deployment-group-name NextjsDeploymentGroup \
            --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},key=deploy.zip,bundleType=zip \
            --region us-east-2
